#!/bin/bash
# chkconfig:   345 98 02
# description: dsmdb in container

### BEGIN INIT INFO
# Provides:       docker-dsmdb
# Required-Start: docker
# Required-Stop:
# Should-Start:
# Should-Stop:
# X-Start-Before: dsm_s
# Default-Start: 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop dsm database container
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

start() {
  /usr/bin/docker start dsmpgsqldb
}

status() {
  /usr/bin/docker ps -a -f "name=dsmpgsqldb"
}

stop() {
  /usr/bin/docker stop dsmpgsqldb
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
esac

exit $?
